# Generated by Django 3.0.2 on 2020-01-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorsModel',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='email_addres',
            new_name='email',
        ),
    ]
